#### COMMENT

### Créer un commentaire
POST http://localhost:3000/newComment
Content-Type: application/json

{
    "text": "Ceci est encore un nouveau commentaire",
    "list_comment_id": 3,
    "user_id": 5
}

### Afficher les commentaires d'une liste de commentaires 
GET http://localhost:3000/comment/3


#### PROJECT

### créer un nouveau projet
POST http://localhost:3000/createProject
Content-Type: application/json

{
    "name": "New Project"
}

### Modifier un projet
PATCH  http://localhost:3000/updateProject
Content-Type: application/json

{
    "name": "New Project",
    "statut": "Terminé",
    "project_id": 13
}

### Afficher le/les projet d'un user
GET http://localhost:3000/projectByUserId/3



### Affiche le/les projets en fonction de la recherche
GET http://localhost:3000/searchProject/ilvoc



### Login
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "albert000@gmail.com",
    "password": "Albert000"
}


#### USER

### Affiche touts les utilisateurs
GET http://localhost:3000/users


### affiche les utilisateurs par leurs rôle
GET http://localhost:3000/usersByRole/graphiste



### Affiche les utilisateurs par leurs id
GET http://localhost:3000/userById/1


### Affiche les utilisateurs en fonction de leur(s) projet(s)
GET http://localhost:3000/usersByProjectId/2



### Création d'un nouvel utilisateur
POST http://localhost:3000/createUser
Content-Type: application/json

{
    "role": "admin",
    "email": "JPMadder2@gmail.com",
    "password": "JPMadder@123",
    "first_name": "jp",
    "last_name": "MADDER",
    "company_name": "",
    "image": ""
}


### Update du password d'un utilisateur
PATCH http://localhost:3000/updateUserPassword
Content-Type: application/json

{
    "password":"Albert0BG",
    "id": 23
}

### Update des informations d'un utilisateur
PATCH http://localhost:3000/updateUser
Content-Type: application/json

{
    "first_name":
    "last_name":
    "company_name":
    "image":
    "id": 3
}




#### COMMENTLIST

### créer une nouvelle liste de commentaires
POST http://localhost:3000/newCommentList
Content-Type: application/json

{
    "sticker_id": 5, 
    "name": "New commentList"
}

### Affiche les commentaires liées à un sticker
GET http://localhost:3000/commentListByStickerId/5



#### FEEDBACK

### Créer un nouveau feeedback
POST http://localhost:3000/newFeedback
Content-Type: application/json

{
    "project_id": 1,
    "user_id": 11,
    "name": "New feedback"
}

### Mettre à jour un feedback
PATCH http://localhost:3000/updateFeedback
Content-Type: application/json

{
    "return_date": "now()",
    "id": 4
}

### Affiche le/les feedback(s) d'un projet
GET http://localhost:3000/feedbackByProjectId/5


#### IMAGE

### Ajouter une nouvelle image
POST http://localhost:3001/newImage
Content-Type: application/json

## 'URl de l'image' attend l'url renvoyées lors de l'upload ↓
{
    "image_url": "URL de l'image",
    "list_image_id": 3,
    "default_height": 230,
    "default_width": 160
}

### Uploader une image
POST http://localhost:3001/uploadImage

###  enctype="multipart/form-data → Voir avec nous.

### Affiche les images en fonction de l'id de leurs list d'image
GET http://localhost:3000/imageByListImageId/3



#### IMAGELIST

### Créer une nouvelle liste d'image
POST http://localhost:3000/newImageList
Content-Type: application/json

{
    "feedback_id": 4,
    "name": "Nouvelle liste d'image"
}

### Affiche la/les liste(s) d'image liées à l'id du feedback
GET http://localhost:3000/imageListByFeedbackId/1



#### STICKER

### Créer un nouveau sticker
POST http://localhost:3000/createnewsticker
Content-Type: application/json

{
    "image_id": 5,
    "position_x": 150,
    "position_y": 200
}

### Afficher les sticker liées à une image
GET http://localhost:3000/findstickers/5


### Modifier l'état d'un sticker
PATCH http://localhost:3000/stickerstateupdate
Content-Type: application/json

{
    "visible": "false", 
    "id": 16
}